# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, gloss }:

cabal.mkDerivation (self: {
  pname = "gameoflife";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ gloss ];
  meta = {
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
